# -*- coding: utf-8 -*-
"""01_engenharia_dados.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIu--ADJfRL4fMDUxq1ya4vK-NkO4gz0
"""

import pandas as pd

# 1. IMPORTANDO OS SEUS "ANALISTAS" (Os 3 arquivos que você já criou)
# Nota: Certifique-se de que o arquivo extracao_cvm.py e filtragem_cvm.py
# estão na mesma pasta/ambiente para que o Python os encontre.
from filtragem_cvm import obter_cnpjs_alvo
from extracao_cvm import coletar_informe_diario_cvm
# from extracao_bcb import coletar_dados_macro  <-- Usaremos este mais para frente!

print("--- INICIANDO O PIPELINE DE DADOS MICROECONÔMICOS ---")

# 2. ACIONANDO A PENEIRA
# Chama a função do seu arquivo filtragem_cvm.py
lista_cnpjs = obter_cnpjs_alvo()

# Trava de segurança: Se a peneira falhar, o código para aqui.
if not lista_cnpjs:
    print("Erro: Nenhum CNPJ capturado. Verifique a conexão com a CVM.")
    exit()

# 3. DEFININDO O PERÍODO DE ESTUDO
meses_estudo = ['202301', '202302']
dados_cvm_consolidados = []

# 4. O CICLO DE EXTRAÇÃO E TRANSFORMAÇÃO (ETL)
for mes in meses_estudo:
    print(f"Baixando e processando o arquivo do mês {mes}...")

    # Chama a função do seu arquivo extracao_cvm.py
    df_mes = coletar_informe_diario_cvm(mes)

    if df_mes is not None:
        # Cruza os dados massivos apenas com os nossos ~24 mil CNPJs válidos
        df_mes_filtrado = df_mes[df_mes['CNPJ_FUNDO'].isin(lista_cnpjs)]

        # Otimização de memória: retém apenas as colunas vitais
        colunas_uteis = ['CNPJ_FUNDO', 'DT_COMPTC', 'VL_QUOTA', 'CAPTC_DIA', 'RESG_DIA', 'VL_PATRIM_LIQ']
        df_mes_filtrado = df_mes_filtrado[colunas_uteis]

        dados_cvm_consolidados.append(df_mes_filtrado)
        print(f"-> Mês {mes}: Retidos {len(df_mes_filtrado)} registros relevantes.")

# 5. CONSOLIDAÇÃO FINAL E ENGENHARIA DE VARIÁVEIS
df_cvm_final = pd.concat(dados_cvm_consolidados, ignore_index=True)

# Converte a data para o formato datetime do Pandas (Crucial para a ANPEC / Econometria)
df_cvm_final['DT_COMPTC'] = pd.to_datetime(df_cvm_final['DT_COMPTC'])

# Cria a variável alvo do nosso estudo: Captação Líquida
df_cvm_final['CAPTACAO_LIQUIDA'] = df_cvm_final['CAPTC_DIA'] - df_cvm_final['RESG_DIA']

print("\n--- RESUMO DA BASE CONSOLIDADA ---")
print(df_cvm_final.info())
print("\nExemplo dos dados finais preparados:")
print(df_cvm_final[['CNPJ_FUNDO', 'DT_COMPTC', 'CAPTACAO_LIQUIDA']].head())

import os

# Lista os arquivos no diretório atual do Colab
arquivos = os.listdir('/content/')

print("Arquivos encontrados no ambiente:")
for arquivo in arquivos:
    print(f"- {arquivo}")

# Verifica especificamente pelos arquivos necessários
print("\n--- Verificação de Dependências ---")
for dep in ['filtragem_cvm.py', 'extracao_cvm.py']:
    if dep in arquivos:
        print(f"✅ {dep} encontrado.")
    else:
        print(f"❌ {dep} NÃO encontrado. Certifique-se de fazer o upload com a extensão .py")

import os

# Lista de arquivos para renomear
arquivos_para_corrigir = ['extracao_cvm', 'filtragem_cvm', 'extracao_bcb']

for nome in arquivos_para_corrigir:
    caminho_antigo = f'/content/{nome}'
    caminho_novo = f'/content/{nome}.py'

    if os.path.exists(caminho_antigo) and not nome.endswith('.py'):
        os.rename(caminho_antigo, caminho_novo)
        print(f"✅ Arquivo '{nome}' renomeado para '{nome}.py'")
    elif os.path.exists(caminho_novo):
        print(f"ℹ️ O arquivo '{nome}.py' já está correto.")
    else:
        print(f"⚠️ Arquivo '{nome}' não encontrado para renomear.")

import pandas as pd

# 1. IMPORTANDO OS SEUS "ANALISTAS"
from filtragem_cvm import obter_cnpjs_alvo
from extracao_cvm import coletar_informe_diario_cvm
# from extracao_bcb import coletar_dados_macro

print("--- INICIANDO O PIPELINE DE DADOS MICROECONÔMICOS ---")

# 2. ACIONANDO A PENEIRA
lista_cnpjs = obter_cnpjs_alvo()

if not lista_cnpjs:
    print("Erro: Nenhum CNPJ capturado. Verifique a conexão com a CVM.")
else:
    # 3. DEFININDO O PERÍODO DE ESTUDO
    meses_estudo = ['202301', '202302']
    dados_cvm_consolidados = []

    # 4. O CICLO DE EXTRAÇÃO E TRANSFORMAÇÃO (ETL)
    for mes in meses_estudo:
        print(f"Baixando e processando o arquivo do mês {mes}...")
        df_mes = coletar_informe_diario_cvm(mes)

        if df_mes is not None:
            df_mes_filtrado = df_mes[df_mes['CNPJ_FUNDO'].isin(lista_cnpjs)]
            colunas_uteis = ['CNPJ_FUNDO', 'DT_COMPTC', 'VL_QUOTA', 'CAPTC_DIA', 'RESG_DIA', 'VL_PATRIM_LIQ']
            df_mes_filtrado = df_mes_filtrado[colunas_uteis]
            dados_cvm_consolidados.append(df_mes_filtrado)
            print(f"-> Mês {mes}: Retidos {len(df_mes_filtrado)} registros relevantes.")

    # 5. CONSOLIDAÇÃO FINAL
    if dados_cvm_consolidados:
        df_cvm_final = pd.concat(dados_cvm_consolidados, ignore_index=True)
        df_cvm_final['DT_COMPTC'] = pd.to_datetime(df_cvm_final['DT_COMPTC'])
        df_cvm_final['CAPTACAO_LIQUIDA'] = df_cvm_final['CAPTC_DIA'] - df_cvm_final['RESG_DIA']

        print("\n--- RESUMO DA BASE CONSOLIDADA ---")
        print(df_cvm_final.info())
        display(df_cvm_final[['CNPJ_FUNDO', 'DT_COMPTC', 'CAPTACAO_LIQUIDA']].head())
    else:
        print("Nenhum dado consolidado.")

codigo_correto = """import pandas as pd
import requests
import io

def obter_cnpjs_alvo() -> list:
    url_cadastro = "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    print("Baixando o cadastro geral de fundos da CVM...")
    try:
        response = requests.get(url_cadastro, headers=headers, timeout=30)
        df_cad = pd.read_csv(io.StringIO(response.text), sep=';', encoding='latin1', low_memory=False)
        df_cad['CLASSE_LIMPA'] = df_cad['CLASSE'].fillna('VAZIO').astype(str).str.strip().str.upper()
        filtro_classe = df_cad['CLASSE_LIMPA'].isin(['MULTIMERCADO', 'RENDA FIXA'])
        df_alvo = df_cad[filtro_classe]
        cnpjs_validos = df_alvo['CNPJ_FUNDO'].unique().tolist()
        print(f"Sucesso! {len(cnpjs_validos)} CNPJs de MM e RF mapeados.")
        return cnpjs_validos
    except Exception as e:
        print(f"Erro no processamento: {e}")
        return []
"""

with open('/content/filtragem_cvm.py', 'w') as f:
    f.write(codigo_correto)

print("✅ Arquivo filtragem_cvm.py corrigido com sucesso! Agora você pode rodar a célula do pipeline.")



codigo_extracao = """import pandas as pd
import requests
import io

def coletar_informe_diario_cvm(periodo: str):
    url = f'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{periodo}.zip'
    headers = {'User-Agent': 'Mozilla/5.0'}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        if response.status_code == 200:
            from zipfile import ZipFile
            with ZipFile(io.BytesIO(response.content)) as z:
                arquivo_csv = z.namelist()[0]
                with z.open(arquivo_csv) as f:
                    return pd.read_csv(f, sep=';', encoding='latin1')
        return None
    except Exception as e:
        print(f'Erro ao baixar {periodo}: {e}')
        return None
"""

with open('/content/extracao_cvm.py', 'w') as f:
    f.write(codigo_extracao)

print("✅ Ambos os arquivos (filtragem e extracao) estão prontos! Pode executar o pipeline.")

import pandas as pd
import importlib
import filtragem_cvm
import extracao_cvm

# Força o recarregamento dos módulos para ler as correções do disco
importlib.reload(filtragem_cvm)
importlib.reload(extracao_cvm)

from filtragem_cvm import obter_cnpjs_alvo
from extracao_cvm import coletar_informe_diario_cvm

print("--- INICIANDO O PIPELINE DE DADOS MICROECONÔMICOS ---")

# 1. Obtendo a lista de CNPJs alvo
lista_cnpjs = obter_cnpjs_alvo()

if not lista_cnpjs:
    print("Erro: Nenhum CNPJ capturado.")
else:
    # 2. Período de estudo
    meses_estudo = ['202301', '202302']
    dados_cvm_consolidados = []

    # 3. ETL - Extração e Filtragem
    for mes in meses_estudo:
        print(f"Processando o mês {mes}...")
        df_mes = coletar_informe_diario_cvm(mes)

        if df_mes is not None:
            df_mes_filtrado = df_mes[df_mes['CNPJ_FUNDO'].isin(lista_cnpjs)]
            colunas_uteis = ['CNPJ_FUNDO', 'DT_COMPTC', 'VL_QUOTA', 'CAPTC_DIA', 'RESG_DIA', 'VL_PATRIM_LIQ']
            df_mes_filtrado = df_mes_filtrado[colunas_uteis]
            dados_cvm_consolidados.append(df_mes_filtrado)
            print(f"-> Mês {mes}: {len(df_mes_filtrado)} registros retidos.")

    # 4. Consolidação e Engenharia de Dados
    if dados_cvm_consolidados:
        df_cvm_final = pd.concat(dados_cvm_consolidados, ignore_index=True)
        df_cvm_final['DT_COMPTC'] = pd.to_datetime(df_cvm_final['DT_COMPTC'])
        df_cvm_final['CAPTACAO_LIQUIDA'] = df_cvm_final['CAPTC_DIA'] - df_cvm_final['RESG_DIA']

        print("\n--- RESUMO DA BASE CONSOLIDADA ---")
        print(df_cvm_final.info())
        display(df_cvm_final[['CNPJ_FUNDO', 'DT_COMPTC', 'CAPTACAO_LIQUIDA']].head())
    else:
        print("Nenhum dado consolidado.")

import pandas as pd
import importlib
import requests
import io

# --- CORREÇÃO DO ARQUIVO extracao_bcb.py ---
codigo_bcb = """import pandas as pd
from bcb import sgs

def coletar_dados_macro(data_inicio, data_fim):
    try:
        # Coletando IPCA (433) e SELIC (11) do SGS/BCB
        df = sgs.get({'IPCA': 433, 'SELIC': 11}, start=data_inicio, end=data_fim)
        return df
    except Exception as e:
        print(f'Erro ao coletar dados do BCB: {e}')
        return None
"""

with open('/content/extracao_bcb.py', 'w') as f:
    f.write(codigo_bcb)

# Instala a biblioteca necessária se não estiver presente
try:
    import bcb
except ImportError:
    !pip install python-bcb

import extracao_bcb
importlib.reload(extracao_bcb)
from extracao_bcb import coletar_dados_macro

print("\n--- INICIANDO INTEGRAÇÃO MACROECONÔMICA (BCB) ---")

# 1. Agregação da Indústria
df_industria_diario = df_cvm_final.groupby('DT_COMPTC').agg(
    CAPTACAO_LIQUIDA_TOTAL=('CAPTACAO_LIQUIDA', 'sum'),
    PL_TOTAL=('VL_PATRIM_LIQ', 'sum')
).reset_index()

# 2. Coleta dos Dados do BCB
data_inicio = df_industria_diario['DT_COMPTC'].min().strftime('%Y-%m-%d')
data_fim = df_industria_diario['DT_COMPTC'].max().strftime('%Y-%m-%d')

print(f"Buscando histórico do BCB de {data_inicio} até {data_fim}...")
df_macro = coletar_dados_macro(data_inicio, data_fim)

if df_macro is not None:
    df_macro = df_macro.reset_index()
    df_macro = df_macro.rename(columns={'Date': 'DT_COMPTC'})
    df_macro['DT_COMPTC'] = pd.to_datetime(df_macro['DT_COMPTC'])

    # 3. Merge
    df_modelo = pd.merge(df_industria_diario, df_macro, on='DT_COMPTC', how='inner')

    print("\n--- BASE FINAL PARA O MODELO ECONOMÉTRICO PRONTA ---")
    print(df_modelo.info())
    display(df_modelo.head())
else:
    print("Falha na extração do BCB.")

import matplotlib.pyplot as plt

print("\n--- GERANDO VISUALIZAÇÃO DE DADOS ---")

# 1. Tratamento da Armadilha do IPCA e Ajuste de Escala
# Descartamos o IPCA para evitar falhas na regressão e dividimos a captação por 1 bilhão para limpar o eixo Y
df_modelo_limpo = df_modelo.drop(columns=['IPCA']).copy()
df_modelo_limpo['CAPTACAO_BILHOES'] = df_modelo_limpo['CAPTACAO_LIQUIDA_TOTAL'] / 1e9

# 2. Configurando a "Prancheta" do Gráfico
fig, ax1 = plt.subplots(figsize=(14, 7))

# Eixo Esquerdo (Y1): Captação Líquida em Barras
cor_barras = '#2c3e50' # Azul escuro institucional
ax1.set_xlabel('Data dos Pregões (Jan-Fev 2023)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Captação Líquida (Bilhões de R$)', color=cor_barras, fontsize=12, fontweight='bold')
ax1.bar(df_modelo_limpo['DT_COMPTC'], df_modelo_limpo['CAPTACAO_BILHOES'], color=cor_barras, alpha=0.7, label='Fluxo de Capital')
ax1.tick_params(axis='y', labelcolor=cor_barras)
ax1.axhline(0, color='black', linewidth=1.2, linestyle='-') # Linha do zero (Breakeven)

# Eixo Direito (Y2): Taxa Selic em Linha
ax2 = ax1.twinx()
cor_linha = '#c0392b' # Vermelho alerta
ax2.set_ylabel('Taxa Selic Diária (%)', color=cor_linha, fontsize=12, fontweight='bold')
ax2.plot(df_modelo_limpo['DT_COMPTC'], df_modelo_limpo['SELIC'], color=cor_linha, linewidth=3, marker='o', label='Selic')
ax2.tick_params(axis='y', labelcolor=cor_linha)

# 3. Acabamento Profissional para o Portfólio
plt.title('O Efeito da Taxa de Juros no Fluxo de Fundos (Multimercado e Renda Fixa)', fontsize=16, fontweight='bold', pad=20)
fig.tight_layout()
plt.grid(axis='x', linestyle='--', alpha=0.4)

# Exibindo
plt.show()

import pandas as pd
import gc # Garbage Collector para limpar a RAM
from filtragem_cvm import obter_cnpjs_alvo
from extracao_cvm import coletar_informe_diario_cvm
from extracao_bcb import coletar_dados_macro

print("--- INICIANDO PIPELINE MACROECONÔMICO DE LONGO PRAZO (2021-2026) ---")

# 1. Aciona a Peneira
lista_cnpjs = obter_cnpjs_alvo()
if not lista_cnpjs:
    print("Erro: Nenhum CNPJ capturado.")
    exit()

# 2. Gerador Dinâmico de Meses
meses_estudo = [f"{ano}{str(mes).zfill(2)}" for ano in range(2021, 2027) for mes in range(1, 13)]
meses_estudo = meses_estudo[:meses_estudo.index('202401') + 1] # Ajustado para jan/2024 para teste

dados_industria_diario = []

# 3. O Loop Otimizado
for mes in meses_estudo:
    print(f"Processando o mês {mes}...")
    df_mes = coletar_informe_diario_cvm(mes)

    if df_mes is not None:
        # --- CORREÇÃO DO KEYERROR: Identifica o nome da coluna de CNPJ ---
        col_cnpj = 'CNPJ_FUNDO' if 'CNPJ_FUNDO' in df_mes.columns else 'CNPJ_FUNDO_CLASSE'

        # Peneira os fundos de interesse usando a coluna correta
        df_mes_filtrado = df_mes[df_mes[col_cnpj].isin(lista_cnpjs)].copy()

        # Garante que as colunas numéricas não deem erro
        for col in ['CAPTC_DIA', 'RESG_DIA', 'VL_PATRIM_LIQ']:
            df_mes_filtrado[col] = pd.to_numeric(df_mes_filtrado[col], errors='coerce').fillna(0)

        # Calcula a Captação Líquida individual
        df_mes_filtrado['CAPTACAO_LIQUIDA'] = df_mes_filtrado['CAPTC_DIA'] - df_mes_filtrado['RESG_DIA']

        # AGREGAÇÃO IMEDIATA
        df_agregado_mes = df_mes_filtrado.groupby('DT_COMPTC').agg(
            CAPTACAO_LIQUIDA_TOTAL=('CAPTACAO_LIQUIDA', 'sum'),
            PL_TOTAL=('VL_PATRIM_LIQ', 'sum')
        ).reset_index()

        dados_industria_diario.append(df_agregado_mes)

        # Limpeza de Memória
        del df_mes
        del df_mes_filtrado
        gc.collect()

# 4. Consolidando
df_cvm_final = pd.concat(dados_industria_diario, ignore_index=True)
df_cvm_final['DT_COMPTC'] = pd.to_datetime(df_cvm_final['DT_COMPTC'])

# 5. Integração BCB
data_inicio = df_cvm_final['DT_COMPTC'].min().strftime('%Y-%m-%d')
data_fim = df_cvm_final['DT_COMPTC'].max().strftime('%Y-%m-%d')

print(f"Buscando dados no BCB ({data_inicio} a {data_fim})...")
df_macro = coletar_dados_macro(data_inicio, data_fim)

if df_macro is not None:
    df_macro = df_macro.reset_index().rename(columns={'Date': 'DT_COMPTC'})
    df_macro['DT_COMPTC'] = pd.to_datetime(df_macro['DT_COMPTC'])

    # Unifica os nomes de colunas do BCB
    col_selic = 'SELIC' if 'SELIC' in df_macro.columns else 'selic_diaria'
    df_macro['SELIC_ANUALIZADA'] = (((1 + (df_macro[col_selic]/100)) ** 252) - 1) * 100

    df_modelo = pd.merge(df_cvm_final, df_macro, on='DT_COMPTC', how='inner')
    df_modelo = df_modelo[['DT_COMPTC', 'CAPTACAO_LIQUIDA_TOTAL', 'PL_TOTAL', 'SELIC_ANUALIZADA']]

    print("\n--- BASE DE DADOS DO MODELO CONCLUÍDA ---")
    display(df_modelo.head())
else:
    print("Falha na coleta do BCB.")

import matplotlib.pyplot as plt

# 1. Preparação dos dados de longo prazo
df_plot = df_modelo.copy()
df_plot['CAPTACAO_BILHOES'] = df_plot['CAPTACAO_LIQUIDA_TOTAL'] / 1e9

# 2. Configuração do Gráfico Comparativo
fig, ax1 = plt.subplots(figsize=(16, 8))

# Eixo Esquerdo: Captação
ax1.set_xlabel('Linha do Tempo (2021 - 2024)', fontsize=12)
ax1.set_ylabel('Captação Líquida Total (Bilhões R$)', color='#2c3e50', fontsize=12, fontweight='bold')
ax1.bar(df_plot['DT_COMPTC'], df_plot['CAPTACAO_BILHOES'], color='#2c3e50', alpha=0.5, label='Fluxo Mensal')
ax1.axhline(0, color='black', linewidth=0.8)

# Eixo Direito: Selic
ax2 = ax1.twinx()
ax2.set_ylabel('Taxa Selic Anualizada (%)', color='#c0392b', fontsize=12, fontweight='bold')
ax2.plot(df_plot['DT_COMPTC'], df_plot['SELIC_ANUALIZADA'], color='#c0392b', linewidth=2.5, label='Selic % p.a.')

# 3. Estética
plt.title('Análise Macro: Captação de Fundos vs. Ciclo de Juros (Selic)', fontsize=16, fontweight='bold')
ax1.grid(True, alpha=0.2)
fig.tight_layout()

plt.show()

print(f"\nResumo Estatístico (Total de {len(df_plot)} dias):")
print(f"Captação Total no Período: R$ {df_plot['CAPTACAO_LIQUIDA_TOTAL'].sum() / 1e9:.2f} Bilhões")
print(f"Patrimônio Médio da Amostra: R$ {df_plot['PL_TOTAL'].mean() / 1e9:.2f} Bilhões")

from google.colab import drive
import os

print("--- INICIANDO EXPORTAÇÃO PARA O GOOGLE DRIVE ---")

# 1. Montando o Drive na máquina virtual do Colab
drive.mount('/content/drive')

# 2. Criando uma pasta dedicada para o seu portfólio (Organização)
caminho_pasta = '/content/drive/MyDrive/Portfolio_Macro_Econometria'

if not os.path.exists(caminho_pasta):
    os.makedirs(caminho_pasta)
    print(f"Pasta criada em: {caminho_pasta}")
else:
    print(f"Pasta já existente em: {caminho_pasta}")

# 3. Definindo o nome do arquivo
caminho_arquivo = f'{caminho_pasta}/dataset_macro_cvm_2021_2024.csv'

# 4. Salvando o DataFrame (index=False evita criar uma coluna extra de numeração)
df_modelo.to_csv(caminho_arquivo, index=False)

print(f"\nSucesso! O seu dataset de {len(df_modelo)} dias úteis foi salvo de forma permanente.")
print(f"Localização no Drive: {caminho_arquivo}")