# -*- coding: utf-8 -*-
"""02_modelagem_econometrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LH6IWQyOfBzQIKJhVx0Ry6KmUEJhIT8b
"""

import pandas as pd
from statsmodels.tsa.stattools import adfuller
from google.colab import drive # <-- A importação vital para novos Notebooks

print("--- CONECTANDO AO GOOGLE DRIVE ---")
# Vai pedir aquela janela de autorização do Google novamente
drive.mount('/content/drive')

print("\n--- INICIANDO TESTES ECONOMÉTRICOS ---")

# 1. Carregando os dados do checkpoint seguro
caminho_arquivo = '/content/drive/MyDrive/Portfolio_Macro_Econometria/dataset_macro_cvm_2021_2024.csv'
df_modelo = pd.read_csv(caminho_arquivo)

def testar_estacionariedade(serie, nome_variavel):
    """
    Aplica o teste ADF para verificar a presença de raiz unitária.
    H0 (Hipótese Nula): A série possui raiz unitária (NÃO é estacionária).
    H1 (Hipótese Alternativa): A série NÃO possui raiz unitária (É estacionária).
    """
    print(f"\n--- Teste Dickey-Fuller Aumentado: {nome_variavel} ---")

    # O adfuller não aceita valores nulos, então garantimos a limpeza com dropna()
    resultado = adfuller(serie.dropna())

    p_value = resultado[1]
    estatistica_adf = resultado[0]

    print(f"Estatística ADF: {estatistica_adf:.4f}")
    print(f"P-value: {p_value:.4f}")

    # Nível de significância estatística rigoroso de 5%
    if p_value < 0.05:
        print("-> CONCLUSÃO: A série é ESTACIONÁRIA (I(0)). O modelo VAR a aceita como está.")
    else:
        print("-> CONCLUSÃO: A série NÃO É ESTACIONÁRIA. Precisaremos aplicar a Primeira Diferença (Δ).")

# 2. Executando o teste para a variável dependente (Y) e independente (X)
testar_estacionariedade(df_modelo['CAPTACAO_LIQUIDA_TOTAL'], 'Captação Líquida dos Fundos')
testar_estacionariedade(df_modelo['SELIC_ANUALIZADA'], 'Taxa Selic Anualizada')

!pip install yfinance

print("--- APLICANDO A PRIMEIRA DIFERENÇA NA SELIC ---")

# 1. Calculando a variação diária da Selic (Diferenciação)
df_modelo['VARIACAO_SELIC'] = df_modelo['SELIC_ANUALIZADA'].diff()

# Ao calcular a diferença, a primeira linha ficará vazia (NaN). Precisamos removê-la.
df_modelo_var = df_modelo.dropna().copy()

print("\n--- Novo Teste Dickey-Fuller: Variação da Selic (Δ) ---")
resultado_diff = adfuller(df_modelo_var['VARIACAO_SELIC'])

print(f"Estatística ADF: {resultado_diff[0]:.4f}")
print(f"P-value: {resultado_diff[1]:.4f}")

if resultado_diff[1] < 0.05:
    print("-> SUCESSO: A Variação da Selic agora é ESTACIONÁRIA. Podemos avançar para o VAR.")
else:
    print("-> ALERTA: A série ainda não é estacionária.")

# 2. Isolando as variáveis finais para o modelo
# Usaremos apenas a Captação e a Variação da Selic
dados_var = df_modelo_var[['CAPTACAO_LIQUIDA_TOTAL', 'VARIACAO_SELIC']]

print("\n--- BASE PREPARADA PARA O MODELO VAR ---")
print(dados_var.head())

from statsmodels.tsa.api import VAR

print("--- SELEÇÃO DE DEFASAGEM (LAGS) DO MODELO VAR ---")

# 1. Inicializa o modelo com a base contendo apenas Captação e Variação da Selic
modelo = VAR(dados_var)

# 2. Testa exaustivamente até 15 dias úteis de defasagem
maximos_dias = 15
resultados_lag = modelo.select_order(maxlags=maximos_dias)

# 3. Imprime o relatório técnico
print("\nResumo dos Critérios de Informação:")
print(resultados_lag.summary())

# 4. Captura a recomendação automática do sistema
lag_ideal_aic = resultados_lag.aic
lag_ideal_bic = resultados_lag.bic

print(f"\n-> O Critério Akaike (AIC) sugere usar {lag_ideal_aic} dias de defasagem.")
print(f"-> O Critério Bayesiano (BIC) sugere usar {lag_ideal_bic} dias de defasagem.")

import statsmodels.api as sm
import matplotlib.pyplot as plt

print("--- PREPARANDO DADOS PARA A REGRESSÃO OLS (MENSAL) ---")

# 1. Transformando a base diária em mensal para capturar o "Efeito Patamar"
# Certifique-se de que a coluna 'DT_COMPTC' está no formato datetime
df_modelo['DT_COMPTC'] = pd.to_datetime(df_modelo['DT_COMPTC'])
# Criamos uma coluna de Ano-Mês
df_modelo['ANO_MES'] = df_modelo['DT_COMPTC'].dt.to_period('M')

# Agrupamos: Somamos a captação do mês e pegamos a média da Selic naquele mês
df_mensal = df_modelo.groupby('ANO_MES').agg(
    CAPTACAO_MENSAL=('CAPTACAO_LIQUIDA_TOTAL', 'sum'),
    SELIC_MEDIA=('SELIC_ANUALIZADA', 'mean')
).reset_index()

# Para facilitar a leitura dos bilhões na tabela do OLS
df_mensal['CAPTACAO_BILHOES'] = df_mensal['CAPTACAO_MENSAL'] / 1e9

print(f"Base convertida de {len(df_modelo)} dias para {len(df_mensal)} meses.\n")

# 2. Configurando o Modelo OLS
# X = Variável Independente (Selic Media) | Y = Variável Dependente (Captação em Bilhões)
X = df_mensal['SELIC_MEDIA']
Y = df_mensal['CAPTACAO_BILHOES']

# O statsmodels exige que adicionemos a constante (o intercepto, Beta 0) manualmente
X_com_constante = sm.add_constant(X)

# 3. Treinando e imprimindo o modelo
modelo_ols = sm.OLS(Y, X_com_constante).fit()
print("--- RESULTADO DA REGRESSÃO (OLS) ---")
print(modelo_ols.summary())

# 4. (Opcional) Visualização Rápida da Linha de Tendência Linear
plt.figure(figsize=(10, 6))
plt.scatter(X, Y, color='#2c3e50', alpha=0.6, label='Meses (Observações)')
plt.plot(X, modelo_ols.predict(X_com_constante), color='#c0392b', linewidth=2, label='Linha de Regressão (OLS)')
plt.axhline(0, color='black', linestyle='--', linewidth=1)
plt.title('Dispersão: Patamar da Selic vs. Fuga de Capital Mensal', fontsize=14, fontweight='bold')
plt.xlabel('Taxa Selic Média do Mês (%)', fontsize=12)
plt.ylabel('Captação Líquida Mensal (Bilhões de R$)', fontsize=12)
plt.legend()
plt.grid(alpha=0.3)
plt.show()

import statsmodels.api as sm
import matplotlib.pyplot as plt

import yfinance as yf
import pandas as pd

print("--- 1. EXTRAINDO O IBOVESPA (CUSTO DE OPORTUNIDADE) ---")
# Baixando o ndice Bovespa direto do Yahoo Finance
ibov = yf.download('^BVSP', start='2021-01-01', end='2026-05-31', progress=False)

# Ajuste para a nova verso do yfinance:
# Se houver MultiIndex, selecionamos o nvel do Preo primeiro
if isinstance(ibov.columns, pd.MultiIndex):
    ibov_close = ibov['Close']['^BVSP']
else:
    ibov_close = ibov['Close']

# Calculando o retorno percentual mensal
ibov_mensal = ibov_close.resample('M').last().pct_change() * 100
ibov_mensal = ibov_mensal.dropna()

# Ajustando o ndice para o formato 'Period'
ibov_mensal.index = ibov_mensal.index.to_period('M')
ibov_mensal.name = 'RETORNO_IBOV'

print("--- 2. CRUZANDO BASES E CRIANDO A DUMMY DE CRISE ---")
df_mult = df_mensal.merge(ibov_mensal, left_on='ANO_MES', right_index=True, how='inner')

df_mult['CRISE_CREDITO'] = 0
df_mult.loc[(df_mult['ANO_MES'] >= '2023-01') & (df_mult['ANO_MES'] <= '2023-04'), 'CRISE_CREDITO'] = 1

print(f"Base unificada com {len(df_mult)} meses processados.")

print("\n--- 3. RODANDO A REGRESSO MLTIPLA (OLS) ---")
Y = df_mult['CAPTACAO_BILHOES']
X_mult = df_mult[['SELIC_MEDIA', 'RETORNO_IBOV', 'CRISE_CREDITO']]

X_mult_const = sm.add_constant(X_mult)
modelo_mult = sm.OLS(Y, X_mult_const).fit()
print(modelo_mult.summary())

print("\n--- 4. VISUALIZAO: REAL VS. PREVISTO ---")
plt.figure(figsize=(14, 7))

eixo_x = df_mult['ANO_MES'].astype(str)

plt.plot(eixo_x, Y, marker='o', color='#2c3e50', linewidth=2, label='Captao Real (CVM)')
plt.plot(eixo_x, modelo_mult.predict(X_mult_const), color='#c0392b', linestyle='--', linewidth=2.5, label='Previso do Modelo (Mltiplo)')

plt.axhline(0, color='black', linewidth=1.2)
plt.title('Capacidade de Previso: O Impacto da Selic, Ibovespa e Eventos de Crdito', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Linha do Tempo (Meses)', fontsize=12, fontweight='bold')
plt.ylabel('Captao Lquida Mensal (Bilhes de R$)', fontsize=12, fontweight='bold')

plt.xticks(rotation=45, ha='right', fontsize=9)
plt.legend(fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

plt.show()

print("--- 2. CRUZANDO BASES E AJUSTANDO A DUMMY DE CRISE ---")
# Fazendo o merge (cruzamento) da nossa base mensal com o Ibovespa
df_mult = df_mensal.merge(ibov_mensal, left_on='ANO_MES', right_index=True, how='inner')

# Criando a Dummy de Crise apontada EXATAMENTE para o Outlier de Junho/2022
df_mult['CRISE_CREDITO'] = 0
df_mult.loc[df_mult['ANO_MES'] == '2022-06', 'CRISE_CREDITO'] = 1

print(f"Base unificada com {len(df_mult)} meses processados.")

print("\n--- 3. RODANDO A REGRESSÃO MÚLTIPLA (OLS) REVISADA ---")
# Definindo Y (Dependente) e a Matriz X (Independentes)
Y = df_mult['CAPTACAO_BILHOES']
X_mult = df_mult[['SELIC_MEDIA', 'RETORNO_IBOV', 'CRISE_CREDITO']]

# Adicionando a constante (Beta 0)
X_mult_const = sm.add_constant(X_mult)

# Treinando o modelo
modelo_mult = sm.OLS(Y, X_mult_const).fit()
print(modelo_mult.summary())

import matplotlib.pyplot as plt

# 4. VISUALIZAO REVISADA: REAL VS. PREVISTO
plt.figure(figsize=(14, 7))

# Convertendo ANO_MES para string para o eixo X
eixo_x = df_mult['ANO_MES'].astype(str)

# Valores Reais
plt.plot(eixo_x, Y, marker='o', color='#2c3e50', linewidth=2, label='Captao Real (CVM)')

# Valores Previstos pelo Modelo
plt.plot(eixo_x, modelo_mult.predict(X_mult_const), color='#c0392b', linestyle='--', linewidth=2.5, label='Previso do Modelo (Revisado)')

# Esttica do Grfico
plt.axhline(0, color='black', linewidth=1.2)
plt.title('Capacidade de Previso: Modelo OLS com Ajuste de Outlier (Jun/22)', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Linha do Tempo (Meses)', fontsize=12, fontweight='bold')
plt.ylabel('Captao Lquida Mensal (Bilhes de R$)', fontsize=12, fontweight='bold')

plt.xticks(rotation=45, ha='right', fontsize=9)
plt.legend(fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

plt.show()